# Generated by Django 5.0.1 on 2024-02-08 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(max_length=50)),
                ('package_validity', models.IntegerField()),
                ('package_price', models.IntegerField()),
                ('package_discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_content_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_certificate', models.CharField(max_length=100)),
                ('details_title', models.CharField(max_length=500)),
                ('details_description', models.TextField()),
                ('details_photo', models.FileField(upload_to='Files/Contents/Posters/')),
                ('details_status', models.IntegerField(default=0)),
                ('details_genres', models.CharField(max_length=50, null=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('language_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_language')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_season', models.IntegerField(default=1)),
                ('content_episode', models.IntegerField(null=True)),
                ('content_file', models.FileField(upload_to='Files/Contents/')),
                ('content_release_date', models.DateField()),
                ('content_duration', models.IntegerField()),
                ('content_title', models.CharField(max_length=500)),
                ('content_description', models.TextField()),
                ('details_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_content_details')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_name', models.CharField(max_length=200)),
                ('crew_role', models.CharField(max_length=200)),
                ('crew_photo', models.FileField(upload_to='Files/Contents/Crew/')),
                ('details_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_content_details')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_release_date', models.DateField()),
                ('trailer_url', models.CharField(max_length=600)),
                ('details_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_content_details')),
            ],
        ),
    ]
