# Generated by Django 5.0.1 on 2024-02-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_content',
            name='content_duration',
            field=models.CharField(max_length=10),
        ),
    ]
