# Generated by Django 5.0.1 on 2024-02-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_tbl_content_content_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_trailer',
            name='trailer_url',
            field=models.URLField(),
        ),
    ]
