# Generated by Django 5.0.1 on 2024-02-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_tbl_trailer_trailer_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_trailer',
        ),
    ]
