# Generated by Django 5.0.1 on 2024-02-08 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_delete_tbl_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_release_date', models.DateField()),
                ('trailer_url', models.URLField()),
                ('details_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_content_details')),
            ],
        ),
    ]
