# Generated by Django 5.0.1 on 2024-02-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_trailer',
            name='trailer_url',
            field=models.CharField(max_length=600),
        ),
    ]
