# Generated by Django 5.0.1 on 2024-02-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_remove_tbl_crew_details_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_content_details',
            name='crew_id',
        ),
        migrations.DeleteModel(
            name='tbl_crew',
        ),
    ]
