# Generated by Django 5.0.1 on 2024-02-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_remove_tbl_content_details_trailer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_content_details',
            name='details_filesize',
            field=models.IntegerField(default=0),
        ),
    ]
