# Generated by Django 5.0.1 on 2024-02-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_content_details_details_filesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_content',
            name='content_season',
            field=models.IntegerField(null=True),
        ),
    ]
