# Generated by Django 5.0.1 on 2024-02-20 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_alter_tbl_content_content_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_name', models.CharField(max_length=200)),
                ('crew_role', models.CharField(max_length=200)),
                ('crew_photo', models.FileField(upload_to='Files/Contents/Crew/')),
                ('details_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_content_details')),
            ],
        ),
    ]
