# Generated by Django 5.0.1 on 2024-03-10 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_crew'),
        ('User', '0011_remove_tbl_watchlist_content_details_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_content_details',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='tbl_content_details',
            name='language_id',
        ),
        migrations.RemoveField(
            model_name='tbl_content_details',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_trailer',
            name='details_id',
        ),
        migrations.RemoveField(
            model_name='tbl_crew',
            name='details_id',
        ),
        migrations.DeleteModel(
            name='tbl_content',
        ),
        migrations.DeleteModel(
            name='tbl_trailer',
        ),
        migrations.DeleteModel(
            name='tbl_content_details',
        ),
        migrations.DeleteModel(
            name='tbl_crew',
        ),
    ]
