# Generated by Django 5.0.1 on 2024-03-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_remove_tbl_content_details_category_id_and_more'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_content_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_certificate', models.CharField(max_length=100)),
                ('details_title', models.CharField(max_length=500)),
                ('details_description', models.TextField()),
                ('details_photo', models.FileField(upload_to='Files/Contents/Posters/')),
                ('details_status', models.IntegerField(default=0)),
                ('details_genres', models.CharField(max_length=50, null=True)),
                ('details_filesize', models.IntegerField(default=0)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('language_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_language')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_season', models.IntegerField(null=True)),
                ('content_episode', models.IntegerField(null=True)),
                ('content_file', models.FileField(upload_to='Files/Contents/')),
                ('content_release_date', models.DateField()),
                ('content_duration', models.CharField(max_length=10)),
                ('content_title', models.CharField(max_length=500)),
                ('content_description', models.TextField()),
                ('details_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_content_details')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_name', models.CharField(max_length=200)),
                ('crew_role', models.CharField(max_length=200)),
                ('crew_photo', models.FileField(upload_to='Files/Contents/Crew/')),
                ('details_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_content_details')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_release_date', models.DateField()),
                ('trailer_url', models.CharField(max_length=600)),
                ('details_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_content_details')),
            ],
        ),
    ]
