# Generated by Django 5.0.1 on 2024-02-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_community',
            name='community_photo',
            field=models.FileField(upload_to='Files/Community/Profile/'),
        ),
    ]
