# Generated by Django 5.0.1 on 2024-02-19 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_tbl_community_community_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_community',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_joinlist',
            name='community_id',
        ),
        migrations.RemoveField(
            model_name='tbl_community_complaint',
            name='community_id',
        ),
        migrations.RemoveField(
            model_name='tbl_community_complaint',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_joinlist',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='tbl_chat',
        ),
        migrations.DeleteModel(
            name='tbl_community',
        ),
        migrations.DeleteModel(
            name='tbl_community_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_joinlist',
        ),
    ]
