# Generated by Django 5.0.1 on 2024-02-19 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('User', '0003_remove_tbl_community_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=200)),
                ('community_date', models.DateField()),
                ('community_photo', models.FileField(upload_to='Files/Community/Profile/')),
                ('community_description', models.TextField()),
                ('community_status', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.TextField()),
                ('chat_date', models.DateField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('community_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_community')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_community_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_community_title', models.CharField(max_length=200)),
                ('cmp_community_content', models.TextField()),
                ('cmp_community_date', models.DateField()),
                ('cmp_community_status', models.IntegerField(default=0)),
                ('cmp_community_replay', models.TextField()),
                ('community_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_community')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_joinlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_status', models.IntegerField(default=0)),
                ('community_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_community')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
