# Generated by Django 5.0.1 on 2024-02-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tbl_community_tbl_chat_tbl_community_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_replay',
            field=models.TextField(null=True),
        ),
    ]
