# Generated by Django 5.0.1 on 2024-02-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_tbl_complaint_complaint_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_replay',
            field=models.TextField(),
        ),
    ]
