# Generated by Django 5.0.1 on 2024-02-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_tbl_complaint_complaint_replay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
