# Generated by Django 5.0.1 on 2024-03-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_tbl_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_replay',
            field=models.TextField(),
        ),
    ]
