# Generated by Django 5.0.1 on 2024-03-11 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_tbl_review_tbl_watchlist_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_watchlist_content',
            name='watchlist_id',
        ),
        migrations.RemoveField(
            model_name='tbl_watchlist_content',
            name='details_id',
        ),
        migrations.DeleteModel(
            name='tbl_watchlist',
        ),
        migrations.DeleteModel(
            name='tbL_watchlist_content',
        ),
    ]
