# Generated by Django 5.0.1 on 2024-03-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_remove_tbl_community_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_review',
        ),
    ]
