# Generated by Django 5.0.1 on 2024-03-13 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_content_details_tbl_content_tbl_crew_tbl_trailer'),
        ('Guest', '0001_initial'),
        ('User', '0016_delete_tbl_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.IntegerField(max_length=20)),
                ('user_review', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('review_datetime', models.DateTimeField(auto_now_add=True)),
                ('details_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_content_details')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
