# Generated by Django 5.0.1 on 2024-03-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_tbl_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_review',
            name='user_rating',
            field=models.IntegerField(),
        ),
    ]
