# Generated by Django 5.0.1 on 2024-03-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_tbl_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_chat',
            old_name='chat_date',
            new_name='chat_time',
        ),
        migrations.RenameField(
            model_name='tbl_chat',
            old_name='from_user_id',
            new_name='from_user',
        ),
    ]
