# Generated by Django 5.0.1 on 2024-03-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_rename_chat_date_tbl_chat_chat_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_chat',
            old_name='from_user',
            new_name='user_from',
        ),
    ]
